{{- if .Values.oc.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "helm_chart.fullname" . }}
  annotations:
    haproxy.router.openshift.io/rewrite-target: / 
spec:
  host: {{ .Values.oc.route.host }}
  path: {{ .Values.context }}
  to:
    kind: Service
    name: {{ include "helm_chart.fullname" . }}
    weight: 100
  port:
    targetPort: http
{{- end }}
